hooks:
  remote:
    repos:
      - id: run-linter
        origin: https://github.com/Rafael24595/hooks
        tag: 0.0.2
        target: golang/sh
        name: run-linter.sh

      - id: run-tests
        origin: https://github.com/Rafael24595/hooks
        tag: 0.0.2
        target: golang/sh
        name: run-tests.sh

      - id: check-large-files
        origin: https://github.com/Rafael24595/hooks
        tag: 0.0.2
        target: golang/sh
        name: check-large-files.sh
        args:
          - 5242880
